// "use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Header } from "@/components/header";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname();
  // const isSignInpage = pathname === "/sign-in";
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} ${inter.className} antialiased`}>
          <Providers>
            {/* {!isSignInpage && ( */}
            <header className="flex justify-end items-center p-4 gap-4 h-16">
              <Header />
            </header>
            {/* )} */}
            <Toaster />
            {children}
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
